/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ProductsIndexImport } from './routes/products/index'
import { Route as ProductsSlugImport } from './routes/products/$slug'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()
const OrderIndexLazyImport = createFileRoute('/order/')()
const OrderCreateLazyImport = createFileRoute('/order/create')()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const OrderIndexLazyRoute = OrderIndexLazyImport.update({
  path: '/order/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/order/index.lazy').then((d) => d.Route))

const ProductsIndexRoute = ProductsIndexImport.update({
  path: '/products/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/products/index.lazy').then((d) => d.Route),
)

const OrderCreateLazyRoute = OrderCreateLazyImport.update({
  path: '/order/create',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/order/create.lazy').then((d) => d.Route))

const ProductsSlugRoute = ProductsSlugImport.update({
  path: '/products/$slug',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/products/$slug.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugImport
      parentRoute: typeof rootRoute
    }
    '/order/create': {
      id: '/order/create'
      path: '/order/create'
      fullPath: '/order/create'
      preLoaderRoute: typeof OrderCreateLazyImport
      parentRoute: typeof rootRoute
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsIndexImport
      parentRoute: typeof rootRoute
    }
    '/order/': {
      id: '/order/'
      path: '/order'
      fullPath: '/order'
      preLoaderRoute: typeof OrderIndexLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  ProductsSlugRoute,
  OrderCreateLazyRoute,
  ProductsIndexRoute,
  OrderIndexLazyRoute,
})

/* prettier-ignore-end */
