/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SlugImport } from './routes/$slug'
import { Route as IndexImport } from './routes/index'
import { Route as OrderIndexImport } from './routes/order/index'
import { Route as ProductsSlugImport } from './routes/products/$slug'

// Create Virtual Routes

const OrderCreateLazyImport = createFileRoute('/order/create')()

// Create/Update Routes

const SlugRoute = SlugImport.update({
  path: '/$slug',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const OrderIndexRoute = OrderIndexImport.update({
  path: '/order/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/order/index.lazy').then((d) => d.Route))

const OrderCreateLazyRoute = OrderCreateLazyImport.update({
  path: '/order/create',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/order/create.lazy').then((d) => d.Route))

const ProductsSlugRoute = ProductsSlugImport.update({
  path: '/products/$slug',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugImport
      parentRoute: typeof rootRoute
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugImport
      parentRoute: typeof rootRoute
    }
    '/order/create': {
      id: '/order/create'
      path: '/order/create'
      fullPath: '/order/create'
      preLoaderRoute: typeof OrderCreateLazyImport
      parentRoute: typeof rootRoute
    }
    '/order/': {
      id: '/order/'
      path: '/order'
      fullPath: '/order'
      preLoaderRoute: typeof OrderIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  SlugRoute,
  ProductsSlugRoute,
  OrderCreateLazyRoute,
  OrderIndexRoute,
})

/* prettier-ignore-end */
